import LayoutMain from "../components/Layout/layoutMain";
import Head from "next/dist/next-server/lib/head";
import styles from "../styles/pages/giris/giris.module.scss";
import Card from "../components/cards/card";
import { PAGE } from "../constants";

function Giris() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutMain fadeBG={true}>
        <div className={styles.container}>
          <Card width="325px" height="333px"></Card>
        </div>
      </LayoutMain>
    </div>
  );
}

export default Giris;
