import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import LayoutMain from "../components/Layout/layoutMain";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutMain>
        <div style={{ height: "100px" }}></div>
      </LayoutMain>
    </div>
  );
}
