import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import LayoutMain from "../components/Layout/layoutMain";
import { PAGE } from "../constants";
import Divider from "../components/divider/divider";
import Link from "next/dist/client/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutMain>
        <Divider direction="left">
          <Link href={PAGE.CokSatanlar.href}>
            <a>{PAGE.CokSatanlar.name}</a>
          </Link>
        </Divider>
        <div style={{ height: "100px" }}></div>
      </LayoutMain>
    </div>
  );
}
