import LayoutMain from "../components/Layout/layoutMain";
import Head from "next/dist/next-server/lib/head";
import styles from "../styles/pages/passwordReset/passwordReset.module.scss";
import Card from "../components/cards/card";
import Form from "../components/forms/form";
import InputText from "../components/inputs/inputText";
import Spacer from "../components/Spacer/spacer";
import { PAGE } from "../constants";
import { useEffect, useState } from "react";
import MainColorButton from "../components/buttons/mainColorButton";
import Swal from "sweetalert2";
import { putData } from "../api/fetch";
import router from "next/router";
import { useRecoilValue } from "recoil";
import { isMobile } from "../states/index.atom";
import LayoutMainMobile from "../components/Layout/layoutMainM";

function PasswordReset() {
  const [disableLoginButton, setDisableLoginButton] = useState(false);
  const isMobileDevice = useRecoilValue(isMobile);

  const onResetPassword = (e) => {
    e.preventDefault();
    const values = Form.getFields();
    let querys = router.query;
    let isFormSuccess = true;

    Object.keys(values).map((item) => {
      if (!values[item].verified) {
        isFormSuccess = false;
        Swal.fire({
          icon: "error",
          title: "Hata!",
          text: "Lütfen en az 6 haneli şifre giriniz.",
        });
      }
    });

    if (isFormSuccess) {
      let sendValues = { id: querys["id"], token: querys["token"] };
      Object.keys(values).map((item) => {
        sendValues[item] = values[item].value;
      });
      setDisableLoginButton(true);
      putData("/api/auth/resetPassword", sendValues)
        .then((res) => {
          Swal.fire({
            icon: "success",
            title: "Başarılı!",
            text: "Şifreniz yenilendi.",
            didClose: () => {
              router.push(PAGE.login.href);
            },
          });
        })
        .catch((err) => {
          if (err.response?.data.code === 1 || err.response?.data.code === 3) {
            Swal.fire({
              icon: "error",
              title: "Hata!",
              text: "Şifre yenileme bağlantınız artık geçersizdir. Lütfen tekrar giriş sayfasından şifremi unuttum kısmına tıklayarak yeniden email gönderin.",
              didClose: () => {
                router.push(PAGE.login.href);
              },
            });
          }
        });

      setDisableLoginButton(false);
    }
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isMobileDevice ? (
        <LayoutMainMobile
          whenAuthDisabledPage={true}
          centerContent={true}
          fadeBG={true}
        >
          <div className={styles.container}>
            <Card width="85vw" height="100%">
              <Form onSubmit={onResetPassword}>
                <InputText
                  labelText="Yeni Şifre"
                  name="password"
                  type="password"
                  pattern="^.{6,}$"
                  width="77vw"
                />
                <Spacer top="24px" />
                <MainColorButton
                  onClick={onResetPassword}
                  type="button"
                  height="44px"
                  text="Şifreyi Yenile"
                  disabled={disableLoginButton}
                />
              </Form>
            </Card>
          </div>
        </LayoutMainMobile>
      ) : (
        <LayoutMain
          whenAuthDisabledPage={true}
          centerContent={true}
          fadeBG={true}
        >
          <div className={styles.container}>
            <Card width="325px" height="100%">
              <Form onSubmit={onResetPassword}>
                <InputText
                  labelText="Yeni Şifre"
                  name="password"
                  type="password"
                  pattern="^.{6,}$"
                />
                <Spacer top="24px" />
                <MainColorButton
                  onClick={onResetPassword}
                  type="button"
                  height="44px"
                  text="Şifreyi Yenile"
                  disabled={disableLoginButton}
                />
              </Form>
            </Card>
          </div>
        </LayoutMain>
      )}
    </div>
  );
}

export default PasswordReset;
