import LayoutMain from "../components/Layout/layoutMain";
import Head from "next/dist/next-server/lib/head";
import styles from "../styles/pages/giris/giris.module.scss";
import Card from "../components/cards/card";
import Form from "../components/forms/form";
import InputText from "../components/inputs/inputText";
import Spacer from "../components/Spacer/spacer";
import { API, PAGE } from "../constants";
import Modal from "../components/modals/modal";
import { useState } from "react";
import MainColorButton from "../components/buttons/mainColorButton";
import WhiteButton from "../components/buttons/whiteButton";
import Link from "next/dist/client/link";
import InputPhoneNumber from "../components/inputs/inputPhoneNumber";
import InputSelect from "../components/inputs/inputSelect";
import Swal from "sweetalert2";
import { postData } from "../api/fetch";
import { useRouter } from "next/router";

function Register() {
  const router = useRouter();
  const [disabledRegisterButton, setDisabledRegisterButton] = useState(false);

  const onRegister = () => {
    let values = Form.getFields();
    let isFormSuccess = true;
    Object.keys(values).map((item) => {
      if (!values[item].verified) {
        isFormSuccess = false;
        Swal.fire({
          icon: "error",
          title: "Hata!",
          text: "Lütfen boş kısımları doldurunuz.",
        });
      }
    });

    if (isFormSuccess) {
      let sendValues = {};
      Object.keys(values).map((item) => {
        sendValues[item] = values[item].value;
      });
      setDisabledRegisterButton(true);
      postData("/api/auth/register", sendValues)
        .then((res) => {
          Swal.fire({
            icon: "success",
            title: "Başarılı!",
            text: "Hesap oluşturuldu",
            didClose: () => {
              router.push(PAGE.login.href);
            },
          });
        })
        .catch((err) => {
          if (err.response.data.code === 2) {
            Swal.fire({
              icon: "error",
              title: "Hata!",
              text: "Bu email adresi ile önceden kayıt olunmuş.",
            });
          } else if (err.response.data.code === 3) {
            Swal.fire({
              icon: "error",
              title: "Hata!",
              text: "Bu telefon numarası ile önceden kayıt olunmuş.",
            });
          }
        });
      setDisabledRegisterButton(false);
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutMain centerContent={true} fadeBG={true}>
        <div className={styles.container}>
          <Spacer top="30px" />
          <Card width="325px" height="100%">
            <Form>
              <InputText
                pattern="^.{3,}$"
                labelText="Ad"
                name="name"
                type="text"
              />
              <Spacer top="16px" />
              <InputText
                pattern="^.{2,}$"
                labelText="Soyad"
                name="surname"
                type="text"
              />
              <Spacer top="16px" />
              <InputText
                pattern="^.{6,}$"
                labelText="Email"
                name="email"
                type="email"
              />
              <Spacer top="16px" />
              <InputText
                pattern="^.{6,}$"
                labelText="Şifre"
                name="password"
                type="password"
              />

              <Spacer top="16px" />
              <InputPhoneNumber
                labelText="Telefon Numarası"
                pattern="^.{10,}$"
                name="phoneNumber"
              />
              <Spacer top="16px" />
              <InputSelect
                options={[
                  { title: "Erkek", value: "male" },
                  { title: "Kadın", value: "female" },
                  { title: "Belirtmek istemiyorum", value: "-" },
                ]}
                labelText="Cinsiyet"
                name="gender"
                pattern="^.{1,}$"
              />

              <Spacer top="24px" />
              <MainColorButton
                onClick={(e) => {
                  e.preventDefault();
                  onRegister();
                }}
                disabled={disabledRegisterButton}
                type="submit"
                height="44px"
                text="Kayıt Ol"
              />
            </Form>
          </Card>
          <Spacer top="30px" />
        </div>
      </LayoutMain>
    </div>
  );
}

export default Register;
