import LayoutMain from "../../components/Layout/layoutMain";
import Head from "next/dist/next-server/lib/head";
import styles from "../../styles/pages/product/product.module.scss";
import Card from "../../components/cards/card";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Navigation, Thumbs } from "swiper/core";
import { useState } from "react";
import LargeCounter from "../../components/counter/largeCounter";
import MainColorButton from "../../components/buttons/mainColorButton";
import ShoppingCartIcon from "../../public/icons/shoppingCart";

function ProductPage() {
  SwiperCore.use([Navigation, Thumbs]);
  const [thumbsSwiper, setThumbsSwiper] = useState(null);
  const [count, setCount] = useState(100);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutMain>
        <div className="productContainerForSwiper">
          <div className={styles.container}>
            <Card className={styles.productPhoto}>
              <Swiper
                thumbs={{ swiper: thumbsSwiper }}
                spaceBetween={25}
                slidesPerView={1}
                className={styles.swiperContainer}
                navigation={true}
                loop={true}
                slidesPerGroup={1}
              >
                {Array(2)
                  .fill(0)
                  .map(() => {
                    return (
                      <SwiperSlide key={1}>
                        <img
                          width="100%"
                          src="https://www.mekecedavetiye.com/Upload/Bannerlar/7.jpg"
                        />
                      </SwiperSlide>
                    );
                  })}
              </Swiper>
              <Swiper
                onSwiper={setThumbsSwiper}
                spaceBetween={10}
                slidesPerView={4}
                freeMode={true}
                watchSlidesVisibility={true}
                watchSlidesProgress={true}
                className="mySwiper"
              >
                {Array(2)
                  .fill(0)
                  .map(() => {
                    return (
                      <SwiperSlide key={1}>
                        <img src="https://www.mekecedavetiye.com/Upload/Bannerlar/7.jpg" />
                      </SwiperSlide>
                    );
                  })}
              </Swiper>
            </Card>
            <div className={styles.rightContainer}>
              <Card className={styles.productCard}>
                <h1 className={styles.productHeader}>
                  Concept Davetiye - 5555
                </h1>
                <h2 className={styles.productPrice}>56.00 TL</h2>
                <div className={styles.counterContainer}>
                  <LargeCounter
                    value={count}
                    onChange={(newCount) => {
                      setCount(count + newCount);
                    }}
                  />
                </div>
                <div className={styles.cartButtonContainer}>
                  <MainColorButton
                    height="44px"
                    text="Sepete Ekle"
                    icon={<ShoppingCartIcon />}
                  />
                </div>
              </Card>
              <Card className={styles.productInfo}>
                <h1 className={styles.productHeader}>Ürün Bilgileri</h1>
                <div className={styles.productDetails}></div>
              </Card>
            </div>
          </div>
        </div>
      </LayoutMain>
    </div>
  );
}

export default ProductPage;
